### ISSUE TITLE
Cannot find module ./cypress/commands/cypress/commands/

### ISSUE THREAD

**Issue by emahuni** [ExpediaGroup/cypress-codegen#191]
I am getting the following error:

```
Cannot find module './cypress/commands/cypress/commands/auth-commands.ts'
```

I have traced the error from the following line in `src/plugin/index.ts`:

```js
  on('task', {
    importCustomCommands: () => {
      return {
        filePaths: globSync(`${COMMANDS_DIRECTORY}/**/*`, { nodir: true }),
        commandsDirectory: `cypress${sep}commands${sep}`
      };
    }
  });
```

to another line in `src/index.ts`:

```js
 const customCommandObject = require(`../../../${projectName}cypress/commands/${filePath.replace(
        commandsDirectory,
        ''
      )}`);
```

Notice that `sep` depends on operating system in node context, but somehow I think that is different with the globing that happens, because I am on Windows and running the whole thing in bash. I think there should be a mix-up of paths somewhere between bash and the OS. To resolve this, I suggest that the commands path be configurable when one configs the plugin itself to make it less opinionated and prone to breaking in different envs. 

For now doing the following should be fine.

```js   
  on('task', {
    importCustomCommands: () => {
      return {
        filePaths: globSync(`${COMMANDS_DIRECTORY}/**/*`, { nodir: true }),
        commandsDirectory:  new RegExp(`cypress[\\\\\\/]commands[\\\\\\/]`, 'g')
      };
    }
  });

```

This allows the replace statement used in `beforeAll` to replace the path regardless of the operating system's sep, hence the import statement can also be safely removed.

**Comment by danadajian** [comment]
@emahuni Thanks for pointing this out! I do realize this plugin does not currently work with pnpm because of the `require()` statement, and also doesn't work with esbuild. I would like to refactor this to add support for both of these, since webpack is basically obsolete these days. However, I could see we would still get some value from simply importing a function that just calls `Cypress.Commands.add()` on everything in a module.

We can release a v2.0.0 that implements your `addModuleCommands()` idea. If you would like to contribute this I would encourage you to do so!

**Comment by danadajian** [comment]
@emahuni Check out version 2.0.0, which contains substantial improvements!

**Comment by danadajian** [comment]
> I didn't see any scooped examples, are they still supported?

We can maybe add support later, but for now I'd recommend adding those commands separately with the desired `prevSubject` option. It would be difficult to support all use cases since there are many options Cypress offers for adding custom commands.
